// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    name, description, logo, industry, phone, email, location, password, customer_signup_code
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, description, logo, industry, phone, email, location, password, plan, customer_signup_code, created_at, updated_at
`

type CreateCompanyParams struct {
	Name               string      `json:"name"`
	Description        pgtype.Text `json:"description"`
	Logo               pgtype.Text `json:"logo"`
	Industry           string      `json:"industry"`
	Phone              string      `json:"phone"`
	Email              string      `json:"email"`
	Location           string      `json:"location"`
	Password           string      `json:"password"`
	CustomerSignupCode string      `json:"customer_signup_code"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.Industry,
		arg.Phone,
		arg.Email,
		arg.Location,
		arg.Password,
		arg.CustomerSignupCode,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.Phone,
		&i.Email,
		&i.Location,
		&i.Password,
		&i.Plan,
		&i.CustomerSignupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, description, logo, industry, phone, email, location, password, plan, customer_signup_code, created_at, updated_at FROM companies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCompany(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.Phone,
		&i.Email,
		&i.Location,
		&i.Password,
		&i.Plan,
		&i.CustomerSignupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByEmail = `-- name: GetCompanyByEmail :one
SELECT id, name, description, logo, industry, phone, email, location, password, plan, customer_signup_code, created_at, updated_at FROM companies
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetCompanyByEmail(ctx context.Context, email string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByEmail, email)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.Phone,
		&i.Email,
		&i.Location,
		&i.Password,
		&i.Plan,
		&i.CustomerSignupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyBySignupCode = `-- name: GetCompanyBySignupCode :one
SELECT id, name, description, logo, industry, phone, email, location, password, plan, customer_signup_code, created_at, updated_at FROM companies
WHERE customer_signup_code = $1 LIMIT 1
`

func (q *Queries) GetCompanyBySignupCode(ctx context.Context, customerSignupCode string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyBySignupCode, customerSignupCode)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.Phone,
		&i.Email,
		&i.Location,
		&i.Password,
		&i.Plan,
		&i.CustomerSignupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, description, logo, industry, phone, email, location, password, plan, customer_signup_code, created_at, updated_at FROM companies
ORDER BY name
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Logo,
			&i.Industry,
			&i.Phone,
			&i.Email,
			&i.Location,
			&i.Password,
			&i.Plan,
			&i.CustomerSignupCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
  set name = $2,
  description = $3,
  logo = $4,
  industry = $5,
  phone = $6,
  email = $7,
  location = $8,
  password = $9,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, logo, industry, phone, email, location, password, plan, customer_signup_code, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Logo        pgtype.Text `json:"logo"`
	Industry    string      `json:"industry"`
	Phone       string      `json:"phone"`
	Email       string      `json:"email"`
	Location    string      `json:"location"`
	Password    string      `json:"password"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.Industry,
		arg.Phone,
		arg.Email,
		arg.Location,
		arg.Password,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.Phone,
		&i.Email,
		&i.Location,
		&i.Password,
		&i.Plan,
		&i.CustomerSignupCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
