// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, created_at, updated_at
`

type CreateCustomerParams struct {
	CompanyID        pgtype.UUID `json:"company_id"`
	Name             string      `json:"name"`
	Email            string      `json:"email"`
	Phone            string      `json:"phone"`
	Password         string      `json:"password"`
	Dob              pgtype.Date `json:"dob"`
	Gender           string      `json:"gender"`
	StateResidence   string      `json:"state_residence"`
	CountryResidence string      `json:"country_residence"`
	Nationality      string      `json:"nationality"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Dob,
		arg.Gender,
		arg.StateResidence,
		arg.CountryResidence,
		arg.Nationality,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, created_at, updated_at FROM customers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, created_at, updated_at FROM customers
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, created_at, updated_at FROM customers
ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Dob,
			&i.Gender,
			&i.StateResidence,
			&i.CountryResidence,
			&i.Nationality,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
  set company_id = coalesce($1, company_id),
  name = coalesce($2, name),
  email = coalesce($3, email),
  phone = coalesce($4, phone),
  password = coalesce($5, password),
  dob = coalesce($6, dob),
  gender = coalesce($7, gender),
  state_residence = coalesce($8, state_residence),
  country_residence = coalesce($9, country_residence),
  nationality = coalesce($10, nationality),
  updated_at = NOW()
WHERE id = $11
RETURNING id, company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, created_at, updated_at
`

type UpdateCustomerParams struct {
	CompanyID        pgtype.UUID `json:"company_id"`
	Name             pgtype.Text `json:"name"`
	Email            pgtype.Text `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Password         pgtype.Text `json:"password"`
	Dob              pgtype.Date `json:"dob"`
	Gender           pgtype.Text `json:"gender"`
	StateResidence   pgtype.Text `json:"state_residence"`
	CountryResidence pgtype.Text `json:"country_residence"`
	Nationality      pgtype.Text `json:"nationality"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.CompanyID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Dob,
		arg.Gender,
		arg.StateResidence,
		arg.CountryResidence,
		arg.Nationality,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
