// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignDriver = `-- name: AssignDriver :one
UPDATE deliveries
SET driver_id = $2, status = 'assigned', updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at
`

type AssignDriverParams struct {
	ID       pgtype.UUID `json:"id"`
	DriverID pgtype.UUID `json:"driver_id"`
}

func (q *Queries) AssignDriver(ctx context.Context, arg AssignDriverParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, assignDriver, arg.ID, arg.DriverID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DriverID,
		&i.PickupAddress,
		&i.DeliveryAddress,
		&i.PickupLat,
		&i.PickupLng,
		&i.DeliveryLat,
		&i.DeliveryLng,
		&i.Status,
		&i.PackageType,
		&i.Weight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (
    customer_id, pickup_address, delivery_address, pickup_lat, pickup_lng, 
    delivery_lat, delivery_lng, package_type, weight, price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at
`

type CreateDeliveryParams struct {
	CustomerID      pgtype.UUID    `json:"customer_id"`
	PickupAddress   string         `json:"pickup_address"`
	DeliveryAddress string         `json:"delivery_address"`
	PickupLat       pgtype.Float8  `json:"pickup_lat"`
	PickupLng       pgtype.Float8  `json:"pickup_lng"`
	DeliveryLat     pgtype.Float8  `json:"delivery_lat"`
	DeliveryLng     pgtype.Float8  `json:"delivery_lng"`
	PackageType     pgtype.Text    `json:"package_type"`
	Weight          pgtype.Float8  `json:"weight"`
	Price           pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.CustomerID,
		arg.PickupAddress,
		arg.DeliveryAddress,
		arg.PickupLat,
		arg.PickupLng,
		arg.DeliveryLat,
		arg.DeliveryLng,
		arg.PackageType,
		arg.Weight,
		arg.Price,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DriverID,
		&i.PickupAddress,
		&i.DeliveryAddress,
		&i.PickupLat,
		&i.PickupLng,
		&i.DeliveryLat,
		&i.DeliveryLng,
		&i.Status,
		&i.PackageType,
		&i.Weight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDelivery = `-- name: DeleteDelivery :exec
DELETE FROM deliveries
WHERE id = $1
`

func (q *Queries) DeleteDelivery(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDelivery, id)
	return err
}

const getDelivery = `-- name: GetDelivery :one
SELECT id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at FROM deliveries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDelivery(ctx context.Context, id pgtype.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DriverID,
		&i.PickupAddress,
		&i.DeliveryAddress,
		&i.PickupLat,
		&i.PickupLng,
		&i.DeliveryLat,
		&i.DeliveryLng,
		&i.Status,
		&i.PackageType,
		&i.Weight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at FROM deliveries
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.DriverID,
			&i.PickupAddress,
			&i.DeliveryAddress,
			&i.PickupLat,
			&i.PickupLng,
			&i.DeliveryLat,
			&i.DeliveryLng,
			&i.Status,
			&i.PackageType,
			&i.Weight,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByCustomer = `-- name: ListDeliveriesByCustomer :many
SELECT id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at FROM deliveries
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveriesByCustomer(ctx context.Context, customerID pgtype.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.DriverID,
			&i.PickupAddress,
			&i.DeliveryAddress,
			&i.PickupLat,
			&i.PickupLng,
			&i.DeliveryLat,
			&i.DeliveryLng,
			&i.Status,
			&i.PackageType,
			&i.Weight,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByDriver = `-- name: ListDeliveriesByDriver :many
SELECT id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at FROM deliveries
WHERE driver_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveriesByDriver(ctx context.Context, driverID pgtype.UUID) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByDriver, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.DriverID,
			&i.PickupAddress,
			&i.DeliveryAddress,
			&i.PickupLat,
			&i.PickupLng,
			&i.DeliveryLat,
			&i.DeliveryLng,
			&i.Status,
			&i.PackageType,
			&i.Weight,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDelivery = `-- name: UpdateDelivery :one
UPDATE deliveries
SET 
  customer_id = coalesce($1, customer_id),
  driver_id = coalesce($2, driver_id),
  pickup_address = coalesce($3, pickup_address),
  delivery_address = coalesce($4, delivery_address),
  pickup_lat = coalesce($5, pickup_lat),
  pickup_lng = coalesce($6, pickup_lng),
  delivery_lat = coalesce($7, delivery_lat),
  delivery_lng = coalesce($8, delivery_lng),
  status = coalesce($9, status),
  package_type = coalesce($10, package_type),
  weight = coalesce($11, weight),
  price = coalesce($12, price),
  updated_at = NOW()
WHERE id = $13
RETURNING id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at
`

type UpdateDeliveryParams struct {
	CustomerID      pgtype.UUID    `json:"customer_id"`
	DriverID        pgtype.UUID    `json:"driver_id"`
	PickupAddress   pgtype.Text    `json:"pickup_address"`
	DeliveryAddress pgtype.Text    `json:"delivery_address"`
	PickupLat       pgtype.Float8  `json:"pickup_lat"`
	PickupLng       pgtype.Float8  `json:"pickup_lng"`
	DeliveryLat     pgtype.Float8  `json:"delivery_lat"`
	DeliveryLng     pgtype.Float8  `json:"delivery_lng"`
	Status          pgtype.Text    `json:"status"`
	PackageType     pgtype.Text    `json:"package_type"`
	Weight          pgtype.Float8  `json:"weight"`
	Price           pgtype.Numeric `json:"price"`
	ID              pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDelivery,
		arg.CustomerID,
		arg.DriverID,
		arg.PickupAddress,
		arg.DeliveryAddress,
		arg.PickupLat,
		arg.PickupLng,
		arg.DeliveryLat,
		arg.DeliveryLng,
		arg.Status,
		arg.PackageType,
		arg.Weight,
		arg.Price,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DriverID,
		&i.PickupAddress,
		&i.DeliveryAddress,
		&i.PickupLat,
		&i.PickupLng,
		&i.DeliveryLat,
		&i.DeliveryLng,
		&i.Status,
		&i.PackageType,
		&i.Weight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :one
UPDATE deliveries
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, customer_id, driver_id, pickup_address, delivery_address, pickup_lat, pickup_lng, delivery_lat, delivery_lng, status, package_type, weight, price, created_at, updated_at
`

type UpdateDeliveryStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryStatus, arg.ID, arg.Status)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DriverID,
		&i.PickupAddress,
		&i.DeliveryAddress,
		&i.PickupLat,
		&i.PickupLng,
		&i.DeliveryLat,
		&i.DeliveryLng,
		&i.Status,
		&i.PackageType,
		&i.Weight,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
