// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDriver = `-- name: CreateDriver :one
INSERT INTO drivers (
    company_id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, available, created_at, updated_at, company_id
`

type CreateDriverParams struct {
	CompanyID        pgtype.UUID `json:"company_id"`
	Name             string      `json:"name"`
	Email            string      `json:"email"`
	Phone            string      `json:"phone"`
	Password         string      `json:"password"`
	Dob              pgtype.Date `json:"dob"`
	Gender           string      `json:"gender"`
	StateResidence   string      `json:"state_residence"`
	CountryResidence string      `json:"country_residence"`
	Nationality      string      `json:"nationality"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, createDriver,
		arg.CompanyID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Dob,
		arg.Gender,
		arg.StateResidence,
		arg.CountryResidence,
		arg.Nationality,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
	)
	return i, err
}

const deleteDriver = `-- name: DeleteDriver :exec
DELETE FROM drivers
WHERE id = $1
`

func (q *Queries) DeleteDriver(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriver, id)
	return err
}

const getDriver = `-- name: GetDriver :one
SELECT id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, available, created_at, updated_at, company_id FROM drivers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDriver(ctx context.Context, id pgtype.UUID) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriver, id)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
	)
	return i, err
}

const getDriverByEmail = `-- name: GetDriverByEmail :one
SELECT id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, available, created_at, updated_at, company_id FROM drivers
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetDriverByEmail(ctx context.Context, email string) (Driver, error) {
	row := q.db.QueryRow(ctx, getDriverByEmail, email)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
	)
	return i, err
}

const listDrivers = `-- name: ListDrivers :many
SELECT id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, available, created_at, updated_at, company_id FROM drivers
ORDER BY name
`

func (q *Queries) ListDrivers(ctx context.Context) ([]Driver, error) {
	rows, err := q.db.Query(ctx, listDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Driver
	for rows.Next() {
		var i Driver
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Dob,
			&i.Gender,
			&i.StateResidence,
			&i.CountryResidence,
			&i.Nationality,
			&i.Available,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriver = `-- name: UpdateDriver :one
UPDATE drivers
  set company_id = coalesce($1, company_id),
  name = coalesce($2, name),
  email = coalesce($3, email),
  phone = coalesce($4, phone),
  password = coalesce($5, password),
  dob = coalesce($6, dob),
  gender = coalesce($7, gender),
  state_residence = coalesce($8, state_residence),
  country_residence = coalesce($9, country_residence),
  nationality = coalesce($10, nationality),
  available = coalesce($11, available),
  updated_at = NOW()
WHERE id = $12
RETURNING id, name, email, phone, password, dob, gender, state_residence, country_residence, nationality, available, created_at, updated_at, company_id
`

type UpdateDriverParams struct {
	CompanyID        pgtype.UUID `json:"company_id"`
	Name             pgtype.Text `json:"name"`
	Email            pgtype.Text `json:"email"`
	Phone            pgtype.Text `json:"phone"`
	Password         pgtype.Text `json:"password"`
	Dob              pgtype.Date `json:"dob"`
	Gender           pgtype.Text `json:"gender"`
	StateResidence   pgtype.Text `json:"state_residence"`
	CountryResidence pgtype.Text `json:"country_residence"`
	Nationality      pgtype.Text `json:"nationality"`
	Available        pgtype.Bool `json:"available"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error) {
	row := q.db.QueryRow(ctx, updateDriver,
		arg.CompanyID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Dob,
		arg.Gender,
		arg.StateResidence,
		arg.CountryResidence,
		arg.Nationality,
		arg.Available,
		arg.ID,
	)
	var i Driver
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Dob,
		&i.Gender,
		&i.StateResidence,
		&i.CountryResidence,
		&i.Nationality,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
	)
	return i, err
}
