// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Logo               pgtype.Text        `json:"logo"`
	Industry           string             `json:"industry"`
	Phone              string             `json:"phone"`
	Email              string             `json:"email"`
	Location           string             `json:"location"`
	Password           string             `json:"password"`
	Plan               interface{}        `json:"plan"`
	CustomerSignupCode string             `json:"customer_signup_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID               pgtype.UUID        `json:"id"`
	CompanyID        pgtype.UUID        `json:"company_id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	Phone            string             `json:"phone"`
	Password         string             `json:"password"`
	Dob              pgtype.Date        `json:"dob"`
	Gender           string             `json:"gender"`
	StateResidence   string             `json:"state_residence"`
	CountryResidence string             `json:"country_residence"`
	Nationality      string             `json:"nationality"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Driver struct {
	ID               pgtype.UUID        `json:"id"`
	CompanyID        pgtype.UUID        `json:"company_id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	Phone            string             `json:"phone"`
	Password         string             `json:"password"`
	Dob              pgtype.Date        `json:"dob"`
	Gender           string             `json:"gender"`
	StateResidence   string             `json:"state_residence"`
	CountryResidence string             `json:"country_residence"`
	Nationality      string             `json:"nationality"`
	Available        pgtype.Bool        `json:"available"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
