// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type VehicleEnum string

const (
	VehicleEnumBike       VehicleEnum = "bike"
	VehicleEnumMotorcycle VehicleEnum = "motorcycle"
	VehicleEnumCar        VehicleEnum = "car"
	VehicleEnumVan        VehicleEnum = "van"
	VehicleEnumTruck      VehicleEnum = "truck"
)

func (e *VehicleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleEnum(s)
	case string:
		*e = VehicleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleEnum: %T", src)
	}
	return nil
}

type NullVehicleEnum struct {
	VehicleEnum VehicleEnum `json:"vehicle_enum"`
	Valid       bool        `json:"valid"` // Valid is true if VehicleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleEnum), nil
}

type Company struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Description        pgtype.Text        `json:"description"`
	Logo               pgtype.Text        `json:"logo"`
	Industry           string             `json:"industry"`
	Phone              string             `json:"phone"`
	Email              string             `json:"email"`
	Location           string             `json:"location"`
	Password           string             `json:"password"`
	Plan               interface{}        `json:"plan"`
	CustomerSignupCode string             `json:"customer_signup_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Customer struct {
	ID               pgtype.UUID        `json:"id"`
	CompanyID        pgtype.UUID        `json:"company_id"`
	Name             string             `json:"name"`
	Email            string             `json:"email"`
	Phone            string             `json:"phone"`
	Password         string             `json:"password"`
	Dob              pgtype.Date        `json:"dob"`
	Gender           string             `json:"gender"`
	StateResidence   string             `json:"state_residence"`
	CountryResidence string             `json:"country_residence"`
	Nationality      string             `json:"nationality"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Delivery struct {
	ID              pgtype.UUID        `json:"id"`
	CustomerID      pgtype.UUID        `json:"customer_id"`
	DriverID        pgtype.UUID        `json:"driver_id"`
	PickupAddress   string             `json:"pickup_address"`
	DeliveryAddress string             `json:"delivery_address"`
	PickupLat       pgtype.Float8      `json:"pickup_lat"`
	PickupLng       pgtype.Float8      `json:"pickup_lng"`
	DeliveryLat     pgtype.Float8      `json:"delivery_lat"`
	DeliveryLng     pgtype.Float8      `json:"delivery_lng"`
	Status          string             `json:"status"`
	PackageType     pgtype.Text        `json:"package_type"`
	Weight          pgtype.Float8      `json:"weight"`
	Price           pgtype.Numeric     `json:"price"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	SuitableVehicle VehicleEnum        `json:"suitable_vehicle"`
}

type Driver struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              string             `json:"email"`
	Phone              string             `json:"phone"`
	Password           string             `json:"password"`
	Dob                pgtype.Date        `json:"dob"`
	Gender             string             `json:"gender"`
	StateResidence     string             `json:"state_residence"`
	CountryResidence   string             `json:"country_residence"`
	Nationality        string             `json:"nationality"`
	Available          pgtype.Bool        `json:"available"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompanyID          pgtype.UUID        `json:"company_id"`
	ActiveDeliveryID   pgtype.UUID        `json:"active_delivery_id"`
	VehicleType        VehicleEnum        `json:"vehicle_type"`
	VehiclePlateNumber string             `json:"vehicle_plate_number"`
	MaxWeightCapacity  float64            `json:"max_weight_capacity"`
	Rating             float64            `json:"rating"`
	TotalDeliveries    int32              `json:"total_deliveries"`
}

type Notification struct {
	ID           pgtype.UUID      `json:"id"`
	ReceiverID   pgtype.UUID      `json:"receiver_id"`
	ReceiverType string           `json:"receiver_type"`
	CompanyID    pgtype.UUID      `json:"company_id"`
	Message      string           `json:"message"`
	Type         string           `json:"type"`
	Read         pgtype.Bool      `json:"read"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
