// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (receiver_id, receiver_type, company_id, message, type, read)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateNotificationParams struct {
	ReceiverID   pgtype.UUID `json:"receiver_id"`
	ReceiverType string      `json:"receiver_type"`
	CompanyID    pgtype.UUID `json:"company_id"`
	Message      string      `json:"message"`
	Type         string      `json:"type"`
	Read         pgtype.Bool `json:"read"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ReceiverID,
		arg.ReceiverType,
		arg.CompanyID,
		arg.Message,
		arg.Type,
		arg.Read,
	)
	return err
}

const getNotifications = `-- name: GetNotifications :many
SELECT id, receiver_id, receiver_type, company_id, message, type, read, created_at, updated_at FROM notifications WHERE receiver_id = $1
`

func (q *Queries) GetNotifications(ctx context.Context, receiverID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotifications, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ReceiverID,
			&i.ReceiverType,
			&i.CompanyID,
			&i.Message,
			&i.Type,
			&i.Read,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications SET read = true WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, id)
	return err
}
