// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignDriver(ctx context.Context, arg AssignDriverParams) (Delivery, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	DeleteCompany(ctx context.Context, id pgtype.UUID) error
	DeleteCustomer(ctx context.Context, id pgtype.UUID) error
	DeleteDelivery(ctx context.Context, id pgtype.UUID) error
	DeleteDriver(ctx context.Context, id pgtype.UUID) error
	GetCompany(ctx context.Context, id pgtype.UUID) (Company, error)
	GetCompanyByEmail(ctx context.Context, email string) (Company, error)
	GetCompanyBySignupCode(ctx context.Context, customerSignupCode string) (Company, error)
	GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetDelivery(ctx context.Context, id pgtype.UUID) (Delivery, error)
	GetDriver(ctx context.Context, id pgtype.UUID) (Driver, error)
	GetDriverByEmail(ctx context.Context, email string) (Driver, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	ListDeliveries(ctx context.Context) ([]Delivery, error)
	ListDeliveriesByCustomer(ctx context.Context, customerID pgtype.UUID) ([]Delivery, error)
	ListDeliveriesByDriver(ctx context.Context, driverID pgtype.UUID) ([]Delivery, error)
	ListDrivers(ctx context.Context) ([]Driver, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateDelivery(ctx context.Context, arg UpdateDeliveryParams) (Delivery, error)
	UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) (Delivery, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (Driver, error)
}

var _ Querier = (*Queries)(nil)
