// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	DeleteCompany(ctx context.Context, id pgtype.UUID) error
	GetCompany(ctx context.Context, id pgtype.UUID) (Company, error)
	GetCompanyByEmail(ctx context.Context, email string) (Company, error)
	GetCompanyBySignupCode(ctx context.Context, customerSignupCode string) (Company, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
}

var _ Querier = (*Queries)(nil)
